Fix a bug in gcd_sircana (#2074)
* Fix a bug in gcd_sircana

So far, we had:

    julia> using Hecke

    julia> R = residue_ring(ZZ,9)[1]
    Integers modulo 9

    julia> S, x = R[:x]
    (Univariate polynomial ring in x over R, x)

    julia> f = x^2 ; g = x^2-5*x+6 ;

    julia> Hecke.gcd_sircana(f,g)
    (x + 6, x + 3, x + 7)

    julia> Hecke.gcd_sircana(f,g*x)
    ERROR: Not an element of the domain
    ...

The last error was due to "lifting" from Z/p to Z/p^2 "directly"
does not work anymore. We now lift to ZZ and project down.

Alas, this is only gets us to the next error. But at least it is
some minor progress.